### ISSUE TITLE
[WTD] PowerBI Consumer Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/powerbi-docs#1047]
In support of #1045 , here is a list of articles with line numbers of where non gender neutral language is present.

- [ ] [end-user-alerts.md Line   #43](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/consumer/end-user-alerts.md#L43)
- [ ] [end-user-basic-concepts.md Line   #103](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/consumer/end-user-basic-concepts.md#L103)
-   [ ] [end-user-comment.md Line   #30](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/consumer/end-user-comment.md#L30)
- [ ] [end-user-comment.md Line   #86](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/consumer/end-user-comment.md#L86)
-   [ ] [end-user-experience.md Line   #20](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/consumer/end-user-experience.md#L20)
- [ ] [end-user-notification-center.md Line   #21](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/consumer/end-user-notification-center.md#L21)
-   [ ] [end-user-q-and-a-tips.md Line   #40](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/consumer/end-user-q-and-a-tips.md#L40)
- [ ] [end-user-q-and-a-tips.md Line   #55](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/consumer/end-user-q-and-a-tips.md#L55)

**Comment by mgblythe** [comment]
Fixed in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2311
