### ISSUE TITLE
[WTD] PowerBI Visuals Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/powerbi-docs#1048]
In support of #1045 , here is a list of articles with line numbers of where non gender neutral language is present.

- [ ] [desktop-shape-map.md Line   #235](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/visuals/desktop-shape-map.md#L235)
- [ ]   [power-bi-visualization-best-practices.md Line   #309](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/visuals/power-bi-visualization-best-practices.md#L309)
-   [ ] [power-bi-visualization-best-practices.md Line   #746](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/visuals/power-bi-visualization-best-practices.md#L746)
- [ ]   [power-bi-visualization-best-practices.md Line   #785](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/visuals/power-bi-visualization-best-practices.md#L785)
-   [ ] [power-bi-visualization-best-practices.md Line   #809](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/visuals/power-bi-visualization-best-practices.md#L809)
- [ ]   [power-bi-visualization-customize-title-background-and-legend.md Line   #22](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/visuals/power-bi-visualization-customize-title-background-and-legend.md#L22)

**Comment by allisongisinger** [comment]
I will work on this

**Comment by allisongisinger** [comment]
Did not update desktop-shape-map.md Line #235 because no changes were required. HE existed in the document, but it was an abbreviation for Hessen, Germany.

**Comment by allisongisinger** [comment]
Did not update lines 746, 785, 809 because specific authors were being talked about and removing the gender or specific references to authors wouldn't make sense for the article.

**Comment by mgblythe** [comment]
Additional work done in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2311
