### ISSUE TITLE
[WTD] PowerBI Desktop Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/powerbi-docs#1049]
In support of #1045 , here is a list of articles with line numbers of where non gender neutral language is present.

- [ ]   [desktop-calculated-columns.md Line   #30](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-calculated-columns.md#L30)
-   [ ] [desktop-calculated-columns.md Line   #36](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-calculated-columns.md#L36)
- [ ] [desktop-calculated-columns.md Line   #42](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-calculated-columns.md#L42)
-   [ ] [desktop-calculated-columns.md Line   #46](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-calculated-columns.md#L46)
- [ ] [desktop-calculated-tables.md Line   #38](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-calculated-tables.md#L38)
-   [ ] [desktop-calculated-tables.md Line   #53](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-calculated-tables.md#L53)
- [ ] [desktop-connect-dataflows.md Line   #42](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-connect-dataflows.md#L42)
-   [ ] [desktop-measures.md Line   #40](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-measures.md#L40)
- [ ] [desktop-measures.md Line   #42](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-measures.md#L42)
-   [ ] [desktop-measures.md Line   #44](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-measures.md#L44)
- [ ] [desktop-measures.md Line   #46](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-measures.md#L46)
-   [ ] [desktop-measures.md Line   #50](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-measures.md#L50)
- [ ] [desktop-measures.md Line   #54](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-measures.md#L54)
-   [ ] [desktop-report-lifecycle-datasets.md Line   #27](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-report-lifecycle-datasets.md#L27)
- [ ] [desktop-report-lifecycle-datasets.md   Line   #31](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-report-lifecycle-datasets.md#L31)
-   [ ] [desktop-report-lifecycle-datasets.md Line   #34](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-report-lifecycle-datasets.md#L34)
- [ ] [desktop-report-lifecycle-datasets.md   Line   #38](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-report-lifecycle-datasets.md#L38)
-   [ ] [desktop-report-lifecycle-datasets.md Line   #40](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-report-lifecycle-datasets.md#L40)
- [ ] [desktop-report-lifecycle-datasets.md   Line   #50](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-report-lifecycle-datasets.md#L50)
-   [ ] [desktop-report-lifecycle-datasets.md Line   #53](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-report-lifecycle-datasets.md#L53)
- [ ] [desktop-report-lifecycle-datasets.md   Line   #57](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-report-lifecycle-datasets.md#L57)
-   [ ] [desktop-report-lifecycle-datasets.md Line   #61](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-report-lifecycle-datasets.md#L61)
- [ ]   [desktop-tutorial-row-level-security-onprem-ssas-tabular.md Line   #111](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-tutorial-row-level-security-onprem-ssas-tabular.md#L111)
-   [ ] [desktop-tutorial-row-level-security-onprem-ssas-tabular.md Line   #113](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-tutorial-row-level-security-onprem-ssas-tabular.md#L113)
- [ ]   [desktop-tutorial-row-level-security-onprem-ssas-tabular.md Line   #121](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-tutorial-row-level-security-onprem-ssas-tabular.md#L121)
-   [ ] [desktop-tutorial-row-level-security-onprem-ssas-tabular.md Line   #131](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/desktop-tutorial-row-level-security-onprem-ssas-tabular.md#L131)

**Comment by mgblythe** [comment]
Fixed in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2311
