### ISSUE TITLE
[WTD] PowerBI Sample Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/powerbi-docs#1050]
In support of #1045 , here is a list of articles with line numbers of where non gender neutral language is present.

- [ ] [sample-customer-profitability.md Line   #19](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L19)
- [ ] [sample-customer-profitability.md Line   #61](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L61)
-   [ ] [sample-customer-profitability.md Line   #76](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L76)
- [ ] [sample-customer-profitability.md Line   #82](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L82)
-   [ ] [sample-customer-profitability.md Line   #97](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L97)
- [ ] [sample-customer-profitability.md Line   #125](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L125)
-   [ ] [sample-customer-profitability.md Line   #126](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L126)
- [ ] [sample-customer-profitability.md Line   #129](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L129)
-   [ ] [sample-customer-profitability.md Line   #133](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L133)
- [ ] [sample-customer-profitability.md Line   #134](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L134)
-   [ ] [sample-customer-profitability.md Line   #135](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L135)
- [ ] [sample-customer-profitability.md Line   #136](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L136)
-   [ ] [sample-customer-profitability.md Line   #141](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L141)
- [ ] [sample-customer-profitability.md Line   #149](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L149)
-   [ ] [sample-customer-profitability.md Line   #150](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L150)
- [ ] [sample-customer-profitability.md Line   #151](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L151)
-   [ ] [sample-customer-profitability.md Line   #152](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-customer-profitability.md#L152)
- [ ] [sample-opportunity-analysis.md Line   #23](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-opportunity-analysis.md#L23)
-   [ ] [sample-opportunity-analysis.md Line   #67](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-opportunity-analysis.md#L67)
- [ ] [sample-opportunity-analysis.md Line   #112](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/sample-opportunity-analysis.md#L112)

**Comment by mgblythe** [comment]
Fixed in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2311
