### ISSUE TITLE
[WTD] PowerBI Service Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/powerbi-docs#1051]
In support of #1045 , here is a list of articles with line numbers of where non gender neutral language is present.

- [ ] [service-admin-faq.md Line   #72](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-admin-faq.md#L72)
- [ ] [service-admin-power-bi-security.md   Line   #54](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-admin-power-bi-security.md#L54)
-   [ ] [service-cortana-troubleshoot.md Line   #56](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-cortana-troubleshoot.md#L56)
- [ ] [service-dashboard-copy.md Line   #20](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-dashboard-copy.md#L20)
-   [ ] [service-data-classification.md Line   #78](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-data-classification.md#L78)
- [ ] [service-dataflows-add-cdm-folder.md   Line   #75](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-dataflows-add-cdm-folder.md#L75)
-   [ ] [service-dataflows-configure-workspace-storage-settings.md Line   #104](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-dataflows-configure-workspace-storage-settings.md#L104)
- [ ]   [service-dataflows-connect-azure-data-lake-storage-gen2.md Line   #183](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md#L183)
-   [ ] [service-from-excel-to-stunning-report.md Line   #70](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-from-excel-to-stunning-report.md#L70)
- [ ]   [service-gateway-high-availability-clusters.md Line   #71](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-gateway-high-availability-clusters.md#L71)
-   [ ] [service-organizational-content-pack-introduction.md Line   #49](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-organizational-content-pack-introduction.md#L49)
- [ ]   [service-organizational-content-pack-introduction.md Line   #53](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-organizational-content-pack-introduction.md#L53)
-   [ ] [service-organizational-content-pack-introduction.md Line   #54](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-organizational-content-pack-introduction.md#L54)
- [ ]   [service-organizational-content-pack-introduction.md Line   #55](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-organizational-content-pack-introduction.md#L55)
-   [ ] [service-organizational-content-pack-introduction.md Line   #58](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-organizational-content-pack-introduction.md#L58)
- [ ]   [service-organizational-content-pack-introduction.md Line   #62](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-organizational-content-pack-introduction.md#L62)
-   [ ] [service-organizational-content-pack-introduction.md Line   #66](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-organizational-content-pack-introduction.md#L66)
- [ ]   [service-organizational-content-pack-introduction.md Line   #69](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-organizational-content-pack-introduction.md#L69)
-   [ ] [service-report-create-new.md Line   #66](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-report-create-new.md#L66)
- [ ] [service-set-data-alerts.md Line   #32](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-set-data-alerts.md#L32)
-   [ ] [service-share-dashboards.md Line   #29](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-share-dashboards.md#L29)
- [ ] [service-share-dashboards.md Line   #105](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-share-dashboards.md#L105)
-   [ ] [service-url-filters.md Line   #26](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/service-url-filters.md#L26)

**Comment by mgblythe** [comment]
Fixed in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2311
