### ISSUE TITLE
[WTD] PowerBI Whitepaper Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/powerbi-docs#1052]
In support of #1045 , here is a list of articles with line numbers of where non gender neutral language is present.

- [ ]   [whitepaper-azure-b2b-power-bi.md Line   #265](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md#L265)
-   [ ] [whitepaper-azure-b2b-power-bi.md Line   #275](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md#L275)
- [ ] [whitepaper-azure-b2b-power-bi.md Line   #330](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md#L330)
-   [ ] [whitepaper-azure-b2b-power-bi.md Line   #362](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md#L362)
- [ ] [whitepaper-azure-b2b-power-bi.md Line   #408](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md#L408)
-   [ ] [whitepaper-azure-b2b-power-bi.md Line   #438](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md#L438)
- [ ] [whitepaper-powerbi-security.md Line   #314](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/whitepaper-powerbi-security.md#L314)

**Comment by Khairunj** [comment]
WTD: Khairun is updating these documentation for gender inclusive

**Comment by mgblythe** [comment]
Fixed in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2311
