### ISSUE TITLE
[WTD] PowerBI Misc Inclusion Articles

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/powerbi-docs#1053]
In support of #1045 , here is a list of articles with line numbers of where non gender neutral language is present.

- [ ]   [power-bi-overview.md Line   #35](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/power-bi-overview.md#L35)
- [ ] [0-0-what-is-power-bi.md Line   #26](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/guided-learning/includes/0-0-what-is-power-bi.md#L26)
- [ ] [0-1-intro-using-power-bi.md Line   #12](https://github.com/MicrosoftDocs/powerbi-docs/edit/live/powerbi-docs/guided-learning/includes/0-1-intro-using-power-bi.md#L12)

**Comment by Khairunj** [comment]
WTD; Khairun is editing these files for write the docs project for inclusive project.

**Comment by mgblythe** [comment]
Fixed in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2311
